### ISSUE TITLE
Rendering Issue with new Icons

### ISSUE THREAD

**Issue by dkh215** [webalys-hq/streamlinehq-npm#14] opened 2021-04-12 16:57 UTC
[Codepen Link](https://codepen.io/markupandstyles/pen/JjELPGY?editors=1000)
### Old Icon vs New Icon
<img width="1440" alt="Screen Shot 2021-04-12 at 11 44 25 AM" src="https://user-images.githubusercontent.com/16489251/114432364-9dcc3800-9b8e-11eb-8fdd-2c1348581ba2.png">

**Comment by dkh215** [comment] 2021-04-12 16:59
It appears there's an issue with the path in the new icon?  I followed the steps to properly download icons from the `    @streamlinehq/streamlinehq` package but after upgrading, I'm having trouble changing the size of the svg. In the picture above, when changing the height from 24px to 16px, a good portion of the svg gets cutoff.

**Comment by cbrwizard** [comment] 2021-04-20 15:07
Hey, could you please check the steps described here https://github.com/webalys-hq/streamlinehq-npm#how-to-change-style-size-etc and check the example app as well https://github.com/webalys-hq/streamlinehq-npm/tree/master/docs/latest/example-app. There you will be able to find the way to change sizes of our SVGs.

Please respond if this resolves your issue

**Comment by dkh215** [comment] 2021-04-21 21:36
Hi @cbrwizard unfortunately I'm still having trouble. I _think_ the issue is that there are hard coded `width` and `height` attributes on the svg files.

<img width="1440" alt="Screen Shot 2021-04-21 at 5 22 25 PM" src="https://user-images.githubusercontent.com/16489251/115624059-138b7e80-a2c8-11eb-8deb-1707e7777fac.png">

**Comment by cbrwizard** [comment] 2021-04-22 10:29
@dkh215 how are you importing the image? I've just updated [the example app](https://github.com/webalys-hq/streamlinehq-npm/blob/master/docs/latest/example-app/src/App.tsx#L67) with an exact image you're trying to use where I reduce its size to 16px. Here is the final result, it doesn't get cut.

<img width="918" alt="Screenshot 2021-04-22 at 13 28 28" src="https://user-images.githubusercontent.com/1615659/115699850-bbf41e00-a36e-11eb-937c-93ef8d705a1f.png">

**Comment by dkh215** [comment] 2021-04-22 13:31
@cbrwizard interesting... I'm importing from the exact same path. I wonder if it's a compatibility issue with [vue-svg-loader](https://github.com/visualfanatic/vue-svg-loader#readme) 🤔 , will dig into this. So weird.

**Comment by cbrwizard** [comment] 2021-04-22 14:19
We're strongly considering wiping all height and width properties from our svgs and setting only viewBox instead (will do this for new icons packs at least). This should solve this issue. No ETA yet though as we're busy with releasing another feature right now

**Comment by Gratouille** [comment] 2021-04-28 13:57
I've just installed the NPM packages and that's a big issue for me, because these height & width properties are killing the "responsiveness" of the SVG icons (with the hard coded `#000` / `currentColor` issue [there](https://github.com/webalys-hq/streamlinehq-npm/issues/15)).

At this time I've added the `[string-replace-loader](https://github.com/Va1/string-replace-loader)`, and I'm using it for deleting these parts before the `file-loader` parses them (as well as replacing any `#000` or `#000000` color code with `currentColor`). It works as intended, but it's quite a downgrade for me.

**Comment by cbrwizard** [comment] 2021-05-18 12:14
Proposed solution is to remove width and height params for all images and to set only viewbox param.

**Comment by pixel-glyph** [comment] 2021-05-22 19:32
Yup, setting a `viewBox` is the correct solution. I'm also running into this issue. Setting `width` and `height` directly on the SVG isn't needed and will not allow it to scale. Unfortunately, I'm also unable to set these imported icons as the `src` on an image tag. I'm following the example app, but the images are broken in the browser. I know it's not my SVG loader since I can import them and use them inline--I just can't scale them.

**Comment by cbrwizard** [comment] 2021-05-24 09:09
Width / height are going to be removed in the following release https://github.com/webalys-hq/streamlinehq-npm/pull/23 and they will have `viewBox` only instead, so this issue will be fixed

**Comment by cbrwizard** [comment] 2021-06-10 12:56
We have recently recreated all assets and released a new NPM 3.0.1 version https://github.com/webalys-hq/streamlinehq-npm/releases/tag/3.0.1, please install it, fetch newest images and check if it helps you. Now width/height are removed, viewBox is added.

**Comment by cbrwizard** [comment] 2021-06-14 15:51
Closing this issue since I believe it's fixed. Feel free to respond if you think otherwise

**Closed by cbrwizard** 2021-06-14 15:51 UTC
Labels: awaiting feedback, bug
