### ISSUE TITLE
Unable to resolve some icons

### ISSUE THREAD

**Issue by stigvanbrabant** [webalys-hq/streamlinehq-npm#16] opened 2021-04-22 09:14 UTC
`
import InterfaceSettingMenuVertical from '@streamlinehq/streamlinehq/img/streamline-bold/interface-setting-menu-vertical-Nc3niS.svg';
`

this icon import fails to resolve, other icons work fine.

version of `@streamlinehq/streamlinehq` is `2.1.0`.

**Comment by sklink** [comment] 2021-04-25 15:18
Quite a few from the `streamline-bold` package are failing to resolve. If you need me to list them out let me know.

**Comment by tomexx** [comment] 2021-05-09 11:32
Yes, a lot of icons, cannot be loaded, e.g.:

```
Module not found: Can't resolve '@streamlinehq/streamlinehq/img/streamline-bold/interface-alert-alarm-bell-2-fSZlC1.svg' ...
```

**Comment by cbrwizard** [comment] 2021-05-18 14:01
Duplicate of https://github.com/webalys-hq/streamlinehq-npm/issues/11
We're working on fixing this

**Closed by cbrwizard** 2021-05-18 14:01 UTC
Labels: bug, in progress
